name: Test Emscripten/Pyodide build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # daily scheduled build at 4am
  schedule:
      - cron: "0 4 * * *"

jobs:
  build-wasm-emscripten:
    runs-on: ubuntu-latest
    env:
      PYODIDE_VERSION: '0.22.0a1'
      PYTHON_VERSION: '3.10.2'
      NODE_VERSION: 18
      EMSCRIPTEN_VERSION: 3.1.24
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache
      
      - name: Install pyodide-build
        run: pip install pyodide-build==$PYODIDE_VERSION

      - name: Download scikit-learn
        run: |
          git clone https://github.com/scikit-learn/scikit-learn --depth 1
          echo scikit-learn commit information
          git -C scikit-learn log -1

      # TODO: cache the wheel and avoid rebuilding
      - name: Build
        run: |
          cd scikit-learn/
          CFLAGS=-g2 LDFLAGS=-g2 pyodide build

          # Make the dist available on the root folder
          cp -r dist ..

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Note: Pyodide venv with scipy doesn't work for now due to https://github.com/pyodide/pyodide/issues/3186
      # - name: install Pyodide
      #   run: |
      #     pyodide venv .venv-pyodide
      # - name: Test
      #   run: |
      #     source .venv-pyodide/bin/activate
      #     pip install scikit-learn/dist/*.whl pytest
      #     pytest --pyargs sklearn.preprocessing

      - name: install Pyodide
        run: |
          npm install pyodide@next
      - name: Test
        run: |
          python run-tests-by-module.py

      - name: Store logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            logs
