name: Test Emscripten/Pyodide build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # daily scheduled build at 4am
  schedule:
      - cron: "0 4 * * *"

jobs:
  build-wasm-emscripten:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download latest Pyodide debug build
        uses: actions/github-script@v6
        with:
          script: |
            var fs = require("fs");
            const owner = "lesteve";
            const repo = "scipy-tests-pyodide";

            const artifacts_response = await github.rest.actions.listArtifactsForRepo({owner: owner, repo: repo});
            console.log(`Found ${artifacts_response.data.total_count} artifacts`);
            artifacts = artifacts_response.data.artifacts;

            const most_recent_artifact = artifacts[0];
            console.log(`action url: https://github.com/${owner}/${repo}/actions/runs/${most_recent_artifact.workflow_run.id}`);
            console.log('artifact:', most_recent_artifact);

            const response = await github.rest.actions.downloadArtifact({
                owner: owner, repo: repo, artifact_id: most_recent_artifact.id, archive_format: "zip"});
            console.log(`Downloaded ${response.data.byteLength / 1000000} MB`);

            await fs.appendFile("pyodide-build.zip", Buffer.from(response.data), function (err) {
                if (err) throw err;
            });

      - name: Unzip Pyodide debug build artifact
        run: |
          unzip pyodide-build.zip -d pyodide
          ls -ltrh pyodide/dist
          # Put back lost permission in artifact
          chmod u+x pyodide/dist/python

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install Pyodide
        run: |
          npm install "pyodide"

      - name: install debug build
        run: |
          cp -r pyodide/dist/* node_modules/pyodide

      - name: Test
        run: |
          python run-tests-by-module.py
