name: Test Emscripten/Pyodide build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # daily scheduled build at 4am
  schedule:
      - cron: "0 4 * * *"

jobs:
  build-wasm-emscripten:
    runs-on: ubuntu-latest
    env:
      PYODIDE_JS_VERSION: '0.22.0'
      PYTHON_VERSION: '3.10.7'
      NODE_VERSION: 18
      EMSCRIPTEN_VERSION: 3.1.29
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download latest Pyodide debug build
        uses: actions/github-script@v6
        with:
          script: |
            var fs = require("fs");
            const owner = "lesteve";
            const repo = "scipy-tests-pyodide";

            const artifacts_response = await github.rest.actions.listArtifactsForRepo({owner: owner, repo: repo});
            console.log(`Found ${artifacts_response.data.total_count} artifacts`);
            artifacts = artifacts_response.data.artifacts;

            const most_recent_artifact = artifacts[0];

            const response = await github.rest.actions.downloadArtifact({
                owner: owner, repo: repo, artifact_id: most_recent_artifact.id, archive_format: "zip"});
            console.log(`Downloaded ${response.data.byteLength / 1000000} MB`);

            await fs.appendFile("pyodide-build.zip", Buffer.from(response.data), function (err) {
                if (err) throw err;
            });

      - name: Unzip Pyodide debug build artifact
        run: |
          unzip pyodide-build.zip -d pyodide-build
          ls -ltrh pyodide-build

      - name: set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Install pyodide-build
        run: |
          git clone https://github.com/pyodide/pyodide --depth 1
          cd pyodide
          pip install -e ./pyodide-build
          pyodide build --help

      - name: Download scikit-learn
        run: |
          git clone https://github.com/scikit-learn/scikit-learn --depth 1
          echo scikit-learn commit information
          git -C scikit-learn log -1

      # TODO: cache the wheel and avoid rebuilding
      - name: Build dev scikit-learn wheel
        run: |
          cd scikit-learn/
          CFLAGS=-g2 LDFLAGS=-g2 pyodide build

          # Make dist accessible at root level
          cp -r dist ../dist

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Note: Pyodide venv with scipy doesn't work for now due to https://github.com/pyodide/pyodide/issues/3186
      # - name: install Pyodide
      #   run: |
      #     pyodide venv .venv-pyodide
      # - name: Test
      #   run: |
      #     source .venv-pyodide/bin/activate
      #     pip install scikit-learn/dist/*.whl pytest
      #     pytest --pyargs sklearn.preprocessing

      - name: install Pyodide
        run: |
          npm install "pyodide@$PYODIDE_JS_VERSION"

      - name: install debug build
        run: |
          ls -ltrh dist
          cp pyodide-build/* node_modules/pyodide

      - name: Test
        run: |
          python run-tests-by-module.py
